const pinyinMap: Record<string, string> = {
  '阿':'a','艾':'ai','安':'an','昂':'ang','奥':'ao',
  '巴':'ba','白':'bai','百':'bai','班':'ban','邦':'bang','包':'bao','北':'bei','本':'ben','崩':'beng','比':'bi','边':'bian','标':'biao','别':'bie','宾':'bin','冰':'bing','波':'bo','布':'bu',
  '才':'cai','财':'cai','采':'cai','蔡':'cai','参':'can','仓':'cang','曹':'cao','策':'ce','岑':'cen','层':'ceng','查':'cha','柴':'chai','产':'chan','长':'chang','超':'chao','车':'che','陈':'chen','成':'cheng','吃':'chi','充':'chong','出':'chu','楚':'chu','川':'chuan','窗':'chuang','吹':'chui','春':'chun','词':'ci','从':'cong','粗':'cu','催':'cui','村':'cun','错':'cuo',
  '达':'da','大':'da','代':'dai','丹':'dan','当':'dang','刀':'dao','德':'de','灯':'deng','地':'di','电':'dian','调':'diao','跌':'die','丁':'ding','东':'dong','斗':'dou','独':'du','度':'du','端':'duan','队':'dui','顿':'dun','多':'duo',
  '额':'e','恩':'en','儿':'er',
  '发':'fa','凡':'fan','方':'fang','飞':'fei','分':'fen','丰':'feng','风':'feng','佛':'fo','否':'fou','夫':'fu','福':'fu',
  '该':'gai','改':'gai','干':'gan','刚':'gang','高':'gao','哥':'ge','格':'ge','根':'gen','更':'geng','工':'gong','共':'gong','狗':'gou','古':'gu','固':'gu','挂':'gua','怪':'guai','关':'guan','光':'guang','归':'gui','国':'guo',
  '哈':'ha','海':'hai','含':'han','行':'hang','豪':'hao','好':'hao','合':'he','和':'he','河':'he','黑':'hei','恨':'hen','横':'heng','红':'hong','后':'hou','呼':'hu','湖':'hu','互':'hu','花':'hua','华':'hua','画':'hua','怀':'huai','坏':'huai','欢':'huan','环':'huan','换':'huan','黄':'huang','回':'hui','会':'hui','混':'hun','活':'huo','火':'huo',
  '几':'ji','机':'ji','鸡':'ji','积':'ji','基':'ji','及':'ji','吉':'ji','极':'ji','急':'ji','集':'ji','籍':'ji','计':'ji','记':'ji','纪':'ji','技':'ji','际':'ji','季':'ji','继':'ji','寄':'ji','加':'jia','家':'jia','假':'jia','价':'jia','架':'jia','嫁':'jia','坚':'jian','间':'jian','肩':'jian','艰':'jian','兼':'jian','监':'jian','煎':'jian','拣':'jian','减':'jian','剪':'jian','检':'jian','简':'jian','见':'jian','件':'jian','建':'jian','剑':'jian','健':'jian','渐':'jian','鉴':'jian','箭':'jian','江':'jiang','姜':'jiang','将':'jiang','奖':'jiang','讲':'jiang','降':'jiang','酱':'jiang','交':'jiao','郊':'jiao','浇':'jiao','骄':'jiao','胶':'jiao','教':'jiao','角':'jiao','脚':'jiao','搅':'jiao','叫':'jiao','较':'jiao','节':'jie','杰':'jie','结':'jie','截':'jie','姐':'jie','解':'jie','介':'jie','界':'jie','届':'jie','戒':'jie','借':'jie','今':'jin','金':'jin','津':'jin','筋':'jin','仅':'jin','紧':'jin','谨':'jin','进':'jin','近':'jin','尽':'jin','劲':'jin','晋':'jin','浸':'jin','禁':'jin','京':'jing','经':'jing','精':'jing','井':'jing','警':'jing','景':'jing','净':'jing','径':'jing','竞':'jing','镜':'jing','究':'jiu','九':'jiu','久':'jiu','酒':'jiu','旧':'jiu','救':'jiu','就':'jiu','居':'ju','举':'ju','具':'ju','句':'ju','巨':'ju','拒':'ju','距':'ju','剧':'ju','据':'ju','聚':'ju','捐':'juan','卷':'juan','倦':'juan','决':'jue','绝':'jue','觉':'jue','掘':'jue','军':'jun','均':'jun','菌':'jun','君':'jun',
  '卡':'ka','开':'kai','凯':'kai','慨':'kai','刊':'kan','看':'kan','康':'kang','扛':'kang','抗':'kang','考':'kao','靠':'kao','科':'ke','棵':'ke','颗':'ke','壳':'ke','咳':'ke','可':'ke','渴':'ke','克':'ke','刻':'ke','客':'ke','课':'ke','肯':'ken','坑':'keng','空':'kong','孔':'kong','恐':'kong','控':'kong','口':'kou','扣':'kou','枯':'ku','哭':'ku','苦':'ku','库':'ku','裤':'ku','酷':'ku','夸':'kua','跨':'kua','块':'kuai','快':'kuai','宽':'kuan','款':'kuan','狂':'kuang','况':'kuang','矿':'kuang','框':'kuang','亏':'kui','昆':'kun','困':'kun','扩':'kuo',
  '拉':'la','啦':'la','来':'lai','蓝':'lan','拦':'lan','栏':'lan','篮':'lan','懒':'lan','烂':'lan','滥':'lan','郎':'lang','狼':'lang','浪':'lang','捞':'lao','劳':'lao','牢':'lao','老':'lao','乐':'le','勒':'le','雷':'lei','累':'lei','类':'lei','冷':'leng','离':'li','梨':'li','狸':'li','厘':'li','李':'li','里':'li','理':'li','力':'li','历':'li','立':'li','丽':'li','利':'li','例':'li','隶':'li','粒':'li','联':'lian','莲':'lian','连':'lian','帘':'lian','怜':'lian','廉':'lian','脸':'lian','练':'lian','炼':'lian','恋':'lian','链':'lian','良':'liang','凉':'liang','粮':'liang','梁':'liang','量':'liang','亮':'liang','两':'liang','辆':'liang','晾':'liang','聊':'liao','疗':'liao','料':'liao','了':'liao','列':'lie','烈':'lie','猎':'lie','裂':'lie','林':'lin','临':'lin','邻':'lin','灵':'ling','铃':'ling','零':'ling','龄':'ling','领':'ling','令':'ling','另':'ling','溜':'liu','刘':'liu','流':'liu','留':'liu','柳':'liu','六':'liu','龙':'long','笼':'long','隆':'long','楼':'lou','漏':'lou','露':'lu','炉':'lu','路':'lu','鹿':'lu','录':'lu','陆':'lu','旅':'lu','绿':'lu','律':'lu','虑':'lu','率':'lv','卵':'luan','乱':'luan','掠':'lue','略':'lue','轮':'lun','论':'lun','落':'luo',
  '妈':'ma','麻':'ma','马':'ma','码':'ma','骂':'ma','吗':'ma','埋':'mai','买':'mai','卖':'mai','麦':'mai','满':'man','曼':'man','慢':'man','漫':'man','忙':'mang','盲':'mang','茫':'mang','猫':'mao','毛':'mao','矛':'mao','茅':'mao','冒':'mao','帽':'mao','貌':'mao','么':'me','没':'mei','眉':'mei','梅':'mei','媒':'mei','煤':'mei','美':'mei','每':'mei','妹':'mei','门':'men','闷':'men','们':'men','蒙':'meng','猛':'meng','梦':'meng','迷':'mi','谜':'mi','米':'mi','密':'mi','秘':'mi','蜜':'mi','棉':'mian','绵':'mian','免':'mian','面':'mian','苗':'miao','描':'miao','秒':'miao','庙':'miao','灭':'mie','民':'min','敏':'min','名':'ming','明':'ming','命':'ming','模':'mo','膜':'mo','磨':'mo','魔':'mo','抹':'mo','末':'mo','莫':'mo','墨':'mo','默':'mo','谋':'mou','某':'mou','母':'mu','木':'mu','目':'mu','牧':'mu','墓':'mu','幕':'mu','慕':'mu','暮':'mu',
  '拿':'na','哪':'na','那':'na','纳':'na','乃':'nai','奶':'nai','耐':'nai','奈':'nai','男':'nan','南':'nan','难':'nan','囊':'nang','脑':'nao','闹':'nao','呢':'ne','内':'nei','嫩':'nen','能':'neng','尼':'ni','泥':'ni','你':'ni','逆':'ni','年':'nian','念':'nian','娘':'niang','鸟':'niao','尿':'niao','捏':'nie','您':'nin','宁':'ning','凝':'ning','牛':'niu','扭':'niu','纽':'niu','农':'nong','浓':'nong','弄':'nong','奴':'nu','努':'nu','怒':'nu','女':'nv','暖':'nuan','挪':'nuo','诺':'nuo',
  '哦':'o','欧':'ou','偶':'ou',
  '拍':'pai','排':'pai','牌':'pai','派':'pai','攀':'pan','盘':'pan','判':'pan','盼':'pan','旁':'pang','胖':'pang','抛':'pao','跑':'pao','泡':'pao','培':'pei','赔':'pei','佩':'pei','配':'pei','盆':'pen','喷':'pen','朋':'peng','棚':'peng','碰':'peng','批':'pi','皮':'pi','疲':'pi','片':'pian','偏':'pian','篇':'pian','骗':'pian','漂':'piao','飘':'piao','票':'piao','拼':'pin','频':'pin','品':'pin','平':'ping','评':'ping','凭':'ping','瓶':'ping','坡':'po','泼':'po','破':'po','迫':'po','扑':'pu','铺':'pu','朴':'pu','普':'pu','谱':'pu',
  '七':'qi','妻':'qi','期':'qi','欺':'qi','齐':'qi','奇':'qi','其':'qi','棋':'qi','旗':'qi','祈':'qi','骑':'qi','起':'qi','启':'qi','气':'qi','弃':'qi','汽':'qi','器':'qi','恰':'qia','千':'qian','迁':'qian','牵':'qian','铅':'qian','谦':'qian','签':'qian','前':'qian','钱':'qian','潜':'qian','浅':'qian','欠':'qian','歉':'qian','枪':'qiang','强':'qiang','墙':'qiang','抢':'qiang','悄':'qiao','桥':'qiao','巧':'qiao','切':'qie','茄':'qie','且':'qie','窃':'qie','亲':'qin','琴':'qin','勤':'qin','青':'qing','轻':'qing','氢':'qing','清':'qing','情':'qing','晴':'qing','请':'qing','庆':'qing','穷':'qiong','秋':'qiu','求':'qiu','球':'qiu','区':'qu','曲':'qu','驱':'qu','趋':'qu','取':'qu','去':'qu','趣':'qu','圈':'quan','全':'quan','权':'quan','泉':'quan','拳':'quan','犬':'quan','劝':'quan','缺':'que','却':'que','确':'que','雀':'que','裙':'qun','群':'qun',
  '然':'ran','燃':'ran','染':'ran','让':'rang','绕':'rao','惹':'re','热':'re','人':'ren','忍':'ren','认':'ren','任':'ren','扔':'reng','仍':'reng','日':'ri','容':'rong','融':'rong','溶':'rong','荣':'rong','柔':'rou','肉':'rou','如':'ru','入':'ru','软':'ruan','瑞':'rui','锐':'rui','润':'run','弱':'ruo',
  '撒':'sa','洒':'sa','塞':'sai','赛':'sai','三':'san','伞':'san','散':'san','桑':'sang','嗓':'sang','扫':'sao','骚':'sao','色':'se','森':'sen','杀':'sha','沙':'sha','纱':'sha','傻':'sha','晒':'shai','筛':'shai','山':'shan','删':'shan','闪':'shan','善':'shan','扇':'shan','伤':'shang','商':'shang','赏':'shang','上':'shang','烧':'shao','稍':'shao','少':'shao','哨':'shao','舌':'she','蛇':'she','舍':'she','社':'she','设':'she','射':'she','涉':'she','摄':'she','申':'shen','伸':'shen','身':'shen','深':'shen','神':'shen','审':'shen','甚':'shen','渗':'shen','慎':'shen','升':'sheng','生':'sheng','声':'sheng','牲':'sheng','绳':'sheng','省':'sheng','圣':'sheng','胜':'sheng','盛':'sheng','尸':'shi','失':'shi','师':'shi','诗':'shi','施':'shi','湿':'shi','十':'shi','石':'shi','时':'shi','识':'shi','实':'shi','拾':'shi','食':'shi','史':'shi','使':'shi','始':'shi','驶':'shi','士':'shi','氏':'shi','世':'shi','市':'shi','示':'shi','式':'shi','事':'shi','势':'shi','是':'shi','适':'shi','室':'shi','释':'shi','收':'shou','手':'shou','守':'shou','首':'shou','寿':'shou','受':'shou','瘦':'shou','兽':'shou','书':'shu','叔':'shu','舒':'shu','疏':'shu','输':'shu','蔬':'shu','熟':'shu','暑':'shu','鼠':'shu','属':'shu','术':'shu','束':'shu','树':'shu','数':'shu','刷':'shua','耍':'shua','摔':'shuai','甩':'shuai','帅':'shuai','双':'shuang','爽':'shuang','水':'shui','睡':'shui','顺':'shun','瞬':'shun','说':'shuo','丝':'si','司':'si','私':'si','思':'si','死':'si','四':'si','寺':'si','似':'si','饲':'si','松':'song','宋':'song','送':'song','颂':'song','搜':'sou','苏':'su','俗':'su','素':'su','速':'su','宿':'su','诉':'su','肃':'su','酸':'suan','蒜':'suan','算':'suan','虽':'sui','随':'sui','岁':'sui','碎':'sui','穗':'sui','孙':'sun','损':'sun','缩':'suo','所':'suo','索':'suo','锁':'suo',
  '他':'ta','她':'ta','它':'ta','塌':'ta','塔':'ta','踏':'ta','台':'tai','抬':'tai','太':'tai','态':'tai','贪':'tan','摊':'tan','滩':'tan','谈':'tan','坦':'tan','探':'tan','叹':'tan','炭':'tan','碳':'tan','汤':'tang','唐':'tang','堂':'tang','塘':'tang','躺':'tang','趟':'tang','烫':'tang','逃':'tao','桃':'tao','陶':'tao','讨':'tao','套':'tao','特':'te','疼':'teng','腾':'teng','踢':'ti','提':'ti','题':'ti','体':'ti','替':'ti','天':'tian','田':'tian','甜':'tian','填':'tian','挑':'tiao','条':'tiao','跳':'tiao','贴':'tie','铁':'tie','厅':'ting','听':'ting','亭':'ting','庭':'ting','停':'ting','挺':'ting','通':'tong','同':'tong','铜':'tong','童':'tong','统':'tong','桶':'tong','痛':'tong','偷':'tou','头':'tou','投':'tou','透':'tou','突':'tu','图':'tu','涂':'tu','途':'tu','土':'tu','吐':'tu','兔':'tu','团':'tuan','推':'tui','腿':'tui','退':'tui','吞':'tun','托':'tuo','拖':'tuo','脱':'tuo','驼':'tuo','妥':'tuo',
  '挖':'wa','蛙':'wa','娃':'wa','瓦':'wa','袜':'wa','歪':'wai','外':'wai','弯':'wan','湾':'wan','丸':'wan','完':'wan','玩':'wan','顽':'wan','挽':'wan','晚':'wan','碗':'wan','万':'wan','汪':'wang','王':'wang','网':'wang','往':'wang','忘':'wang','望':'wang','危':'wei','威':'wei','微':'wei','围':'wei','违':'wei','唯':'wei','维':'wei','伟':'wei','尾':'wei','委':'wei','卫':'wei','未':'wei','位':'wei','味':'wei','胃':'wei','畏':'wei','喂':'wei','谓':'wei','慰':'wei','温':'wen','文':'wen','纹':'wen','闻':'wen','稳':'wen','问':'wen','翁':'weng','窝':'wo','我':'wo','握':'wo','乌':'wu','污':'wu','屋':'wu','无':'wu','吴':'wu','五':'wu','午':'wu','伍':'wu','武':'wu','舞':'wu','务':'wu','物':'wu','误':'wu','悟':'wu',
  '夕':'xi','西':'xi','吸':'xi','希':'xi','息':'xi','悉':'xi','牺':'xi','惜':'xi','溪':'xi','锡':'xi','熄':'xi','习':'xi','席':'xi','袭':'xi','洗':'xi','喜':'xi','戏':'xi','系':'xi','细':'xi','虾':'xia','瞎':'xia','峡':'xia','侠':'xia','狭':'xia','下':'xia','夏':'xia','吓':'xia','先':'xian','仙':'xian','鲜':'xian','纤':'xian','咸':'xian','贤':'xian','闲':'xian','弦':'xian','嫌':'xian','显':'xian','险':'xian','县':'xian','现':'xian','线':'xian','限':'xian','宪':'xian','陷':'xian','羡':'xian','献':'xian','乡':'xiang','相':'xiang','香':'xiang','箱':'xiang','详':'xiang','享':'xiang','响':'xiang','想':'xiang','向':'xiang','象':'xiang','像':'xiang','项':'xiang','消':'xiao','硝':'xiao','销':'xiao','小':'xiao','晓':'xiao','孝':'xiao','效':'xiao','笑':'xiao','校':'xiao','些':'xie','歇':'xie','鞋':'xie','协':'xie','斜':'xie','携':'xie','写':'xie','泄':'xie','泻':'xie','卸':'xie','谢':'xie','心':'xin','辛':'xin','欣':'xin','新':'xin','薪':'xin','信':'xin','星':'xing','兴':'xing','刑':'xing','型':'xing','形':'xing','醒':'xing','幸':'xing','性':'xing','姓':'xing','凶':'xiong','胸':'xiong','雄':'xiong','熊':'xiong','休':'xiu','修':'xiu','秀':'xiu','绣':'xiu','锈':'xiu','袖':'xiu','虚':'xu','需':'xu','须':'xu','许':'xu','序':'xu','叙':'xu','续':'xu','蓄':'xu','畜':'xu','绪':'xu','宣':'xuan','悬':'xuan','旋':'xuan','选':'xuan','玄':'xuan','削':'xue','穴':'xue','学':'xue','雪':'xue','血':'xue','寻':'xun','巡':'xun','循':'xun','训':'xun','讯':'xun','迅':'xun',
  '压':'ya','鸭':'ya','牙':'ya','芽':'ya','雅':'ya','亚':'ya','咽':'yan','烟':'yan','淹':'yan','盐':'yan','严':'yan','言':'yan','岩':'yan','沿':'yan','炎':'yan','研':'yan','眼':'yan','演':'yan','厌':'yan','验':'yan','艳':'yan','雁':'yan','宴':'yan','燕':'yan','央':'yang','扬':'yang','羊':'yang','阳':'yang','杨':'yang','仰':'yang','养':'yang','样':'yang','妖':'yao','腰':'yao','邀':'yao','摇':'yao','遥':'yao','咬':'yao','药':'yao','要':'yao','钥':'yao','耀':'yao','爷':'ye','也':'ye','野':'ye','业':'ye','叶':'ye','页':'ye','夜':'ye','液':'ye','一':'yi','衣':'yi','医':'yi','依':'yi','仪':'yi','宜':'yi','姨':'yi','遗':'yi','移':'yi','疑':'yi','乙':'yi','已':'yi','以':'yi','椅':'yi','蚁':'yi','亿':'yi','义':'yi','艺':'yi','忆':'yi','议':'yi','译':'yi','异':'yi','益':'yi','意':'yi','毅':'yi','抑':'yi','因':'yin','阴':'yin','音':'yin','银':'yin','引':'yin','饮':'yin','隐':'yin','印':'yin','英':'ying','应':'ying','樱':'ying','鹰':'ying','迎':'ying','盈':'ying','营':'ying','赢':'ying','影':'ying','映':'ying','硬':'ying','拥':'yong','永':'yong','勇':'yong','涌':'yong','用':'yong','优':'you','忧':'you','悠':'you','尤':'you','由':'you','油':'you','游':'you','友':'you','有':'you','又':'you','右':'you','幼':'you','于':'yu','余':'yu','鱼':'yu','娱':'yu','渔':'yu','愉':'yu','逾':'yu','宇':'yu','羽':'yu','雨':'yu','语':'yu','玉':'yu','育':'yu','域':'yu','欲':'yu','遇':'yu','御':'yu','豫':'yu','誉':'yu','浴':'yu','预':'yu','寓':'yu','裕':'yu','冤':'yuan','元':'yuan','园':'yuan','员':'yuan','原':'yuan','圆':'yuan','源':'yuan','远':'yuan','院':'yuan','愿':'yuan','约':'yue','月':'yue','阅':'yue','悦':'yue','越':'yue','跃':'yue','云':'yun','匀':'yun','允':'yun','运':'yun','韵':'yun',
  '杂':'za','砸':'za','灾':'zai','栽':'zai','载':'zai','再':'zai','在':'zai','咱':'zan','赞':'zan','暂':'zan','脏':'zang','葬':'zang','遭':'zao','糟':'zao','早':'zao','澡':'zao','灶':'zao','造':'zao','噪':'zao','则':'ze','责':'ze','择':'ze','贼':'zei','怎':'zen','增':'zeng','赠':'zeng','扎':'zha','眨':'zha','炸':'zha','摘':'zhai','窄':'zhai','债':'zhai','寨':'zhai','沾':'zhan','粘':'zhan','展':'zhan','占':'zhan','战':'zhan','站':'zhan','张':'zhang','章':'zhang','掌':'zhang','丈':'zhang','仗':'zhang','帐':'zhang','账':'zhang','障':'zhang','招':'zhao','朝':'zhao','照':'zhao','罩':'zhao','遮':'zhe','折':'zhe','哲':'zhe','者':'zhe','这':'zhe','浙':'zhe','针':'zhen','珍':'zhen','真':'zhen','诊':'zhen','枕':'zhen','阵':'zhen','振':'zhen','镇':'zhen','争':'zheng','征':'zheng','挣':'zheng','睁':'zheng','蒸':'zheng','整':'zheng','正':'zheng','证':'zheng','政':'zheng','症':'zheng','之':'zhi','支':'zhi','汁':'zhi','知':'zhi','织':'zhi','脂':'zhi','执':'zhi','直':'zhi','值':'zhi','职':'zhi','植':'zhi','殖':'zhi','止':'zhi','只':'zhi','旨':'zhi','指':'zhi','纸':'zhi','至':'zhi','志':'zhi','制':'zhi','质':'zhi','治':'zhi','致':'zhi','智':'zhi','置':'zhi','中':'zhong','忠':'zhong','钟':'zhong','终':'zhong','种':'zhong','众':'zhong','重':'zhong','周':'zhou','洲':'zhou','粥':'zhou','轴':'zhou','肘':'zhou','皱':'zhou','骤':'zhou','珠':'zhu','朱':'zhu','猪':'zhu','竹':'zhu','烛':'zhu','主':'zhu','煮':'zhu','嘱':'zhu','住':'zhu','注':'zhu','驻':'zhu','柱':'zhu','祝':'zhu','著':'zhu','助':'zhu','筑':'zhu','抓':'zhua','爪':'zhua','拽':'zhuai','专':'zhuan','砖':'zhuan','转':'zhuan','赚':'zhuan','装':'zhuang','壮':'zhuang','撞':'zhuang','状':'zhuang','追':'zhui','准':'zhun','捉':'zhuo','桌':'zhuo','着':'zhuo','浊':'zhuo','资':'zi','姿':'zi','滋':'zi','子':'zi','紫':'zi','字':'zi','自':'zi','宗':'zong','综':'zong','总':'zong','纵':'zong','走':'zou','租':'zu','足':'zu','族':'zu','阻':'zu','组':'zu','祖':'zu','嘴':'zui','醉':'zui','最':'zui','罪':'zui','尊':'zun','遵':'zun','昨':'zuo','左':'zuo','做':'zuo','作':'zuo','坐':'zuo','座':'zuo'
}

const charToPinyin = new Map<string, string>()
for (const [char, py] of Object.entries(pinyinMap)) {
  charToPinyin.set(char, py)
}

export function getPinyinInitials(text: string): string {
  let initials = ''
  for (const char of text) {
    const py = charToPinyin.get(char)
    if (py) {
      initials += py[0]
    } else if (/[a-zA-Z]/.test(char)) {
      initials += char.toLowerCase()
    }
  }
  return initials
}

export function getPinyinFull(text: string): string {
  let full = ''
  for (const char of text) {
    const py = charToPinyin.get(char)
    if (py) {
      full += py
    } else {
      full += char.toLowerCase()
    }
  }
  return full
}

export function matchPinyin(query: string, text: string): boolean {
  const lowerQuery = query.toLowerCase()
  const lowerText = text.toLowerCase()

  if (lowerText.includes(lowerQuery)) return true

  const fullPinyin = getPinyinFull(text)
  if (fullPinyin.includes(lowerQuery)) return true

  const initials = getPinyinInitials(text)
  if (initials.includes(lowerQuery)) return true

  return false
}
